### ISSUE TITLE
nn not work in Pry (0.12.2)

### ISSUE THREAD

**Issue by zw963** [garmoshka-mo/pry-moves#6]
I think a example is more clear to clarify.

### create a new rb file `1.rb` (pry! is a wrapper)

```rb
# 1.rb
puts 100

def hello
  x = '1'
  y = '2'
  x + y
end

def hello1
  yield '1'
  yield '2'
end

pry!
hello
hello1 do |e|
  x = e
  y = e
  x + y
end

puts 200
```

### run `ruby 1.rb` to execute this rb file, and following is reproduce

```rb
╰─ $ ruby 1.rb 
100
loading pry ...

Frame: 0/9 main
From: /home/zw963/others/.rvm/gems/ruby-2.6.2@pry/gems/1.rb:14 main

     4:   x = '1'
     5:   y = '2'
     6:   x + y
     7: end
     8: 
     9: def hello1
    10:   yield '1'
    11:   yield '2'
    12: end
    13: 
 => 14: pry!
    15: hello
    16: hello1 do |e|
    17:   x = e
    18:   y = e
    19:   x + y
    20: end
    21: 
    22: puts 200

(pry):main(0)> nn
frame_digest for:
frame_digest for:

Frame: 0/6
From: /home/zw963/others/.rvm/gems/ruby-2.6.2@pry/gems/1.rb:15 main

     5:   y = '2'
     6:   x + y
     7: end
     8:
     9: def hello1
    10:   yield '1'
    11:   yield '2'
    12: end
    13:
    14: pry!
 => 15: hello
    16: hello1 do |e|
    17:   x = e
    18:   y = e
    19:   x + y
    20: end
    21:
    22: puts 200

(pry):main(0)> nn
frame_digest for:
Traceback (most recent call last):
        10: from 1.rb:15:in `<main>'
         9: from /home/public/Dropbox/common/ruby/pry/pry-moves/tracer.rb:109:in `tracing_func'
         8: from /home/public/Dropbox/common/ruby/pry/pry-moves/tracer.rb:109:in `catch'
         7: from /home/public/Dropbox/common/ruby/pry/pry-moves/tracer.rb:112:in `block in tracing_func'
         6: from /home/public/Dropbox/common/ruby/pry/pry-moves/pry_ext.rb:9:in `start_with_pry_nav'
         5: from /home/public/Dropbox/common/ruby/pry/pry-moves/pry_wrapper.rb:25:in `run'
         4: from /home/public/Dropbox/common/ruby/pry/pry-moves/pry_wrapper.rb:42:in `trace_command'
         3: from /home/public/Dropbox/common/ruby/pry/pry-moves/pry_wrapper.rb:77:in `start_tracing'
         2: from /home/public/Dropbox/common/ruby/pry/pry-moves/tracer.rb:41:in `trace'
         1: from /home/public/Dropbox/common/ruby/pry/pry-moves/tracer.rb:100:in `frame_digest'
/home/public/Dropbox/common/ruby/lib/debugrc.rb:84:in `method_missing': undefined method `disasm' for nil:NilClass (NoMethodError)

```

### current version

Pry version 0.12.2 on Ruby 2.6.2
pry-moves 0.1.10

(Do some hack for pry-moves work with pry 0.12.2)

Thanks

**Comment by zw963** [comment]
Hi, after update to use github master (a2196ab), it worked now.

**Comment by zw963** [comment]
There is a edge case where i have to to do make `pry-moves` work `with pry-stack_explorer`.

1. remove `pry-moves/lib/pry-stack_explorer/pry-stack_explorer.rb`.
2. change `pry-stack_explorer/lib/pry-stack_explorer.rb` content same as above file.
3. remove require statement in `pry-moves/lib/pry-moves.rb`.
4. require 'pry-stack_explorer' gem in .irbrc.

If don't do this, when run pry in console, got:

```rb
 ╰─ $ pry

Frame: 0/4 method
From: /home/public/Dropbox/common/ruby/pry/pry-moves/pry_ext.rb:14 Pry

     4: def start_with_pry_nav(target = TOPLEVEL_BINDING, options = {}) # target: #<Binding:0x
     5:   old_options = options.reject { |k, _| k == :pry_remote } # old_options: {:input=>#<S
     6:
     7:   if target.is_a?(Binding) && PryMoves.check_file_context(target)
     8:     # Wrap the tracer around the usual Pry.start
     9:     PryMoves::PryWrapper.new(target, options).run do
    10:       start_without_pry_nav(target, old_options)
    11:     end
    12:   else
    13:     # No need for the tracer unless we have a file context to step through
 => 14:     start_without_pry_nav(target, old_options)
    15:   end
    16: end

(pry):Pry(0)>
```

But, when use with `binding.pry`, it work as expected.

**Comment by zw963** [comment]
Hi, i don't know why, but i think this gem still not working with pry-stack_explorer.

i have to revert all code changed to pry-stack_explorer (Yes, just  use default pry-stack_explorer 0.8.0, and drop all code tthis gem changed to pry-stack_explorer).


If don't do this, when i have a wrapper func like this:

```rb
def _pry(host=nil, port=nil, options={})
    
    # ...

    if host
      warn '[1m[33mloading remote pry ...[0m'
      remote_pry(host, port, options) if Pry.initial_session?
    else
      warn '[1m[33mloading pry ...[0m'
      pry
    end
  end
```

When run pry like this:

```rb
# ....
binding._pry
```

Got following unexpected output:

```rb
    42:
    43:     if host
    44:       warn 'loading remote pry ...'
    45:       remote_pry(host, port, options) if Pry.initial_session?
    46:     else
    47:       warn 'loading pry ...'
 => 48:       pry
    49:     end
    50:   end
    51: end
```

And, where `=>` position is inside that wrapper method.

If revert to use default  pry-stack_explorer, `pry-nav` work very well, pry-moves most
command works too. e.g. continue, step, next, show-stack, debug, step back, finish, up down.

nn still not work as this issue describe.
